# Config file for automatic testing at travis-ci.org
dist: xenial

language: python

python:
  - 3.6
  - 3.7

os:
  - linux

cache:
  - pip

notifications:
  email: false

before_install:
  - sudo apt-get install jq
  - curl -LSs "$(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')" -o codacy-coverage-reporter-assembly.jar

install:
  - pip install pytest-cov
  - pip install --quiet .[test,notebooks]

script:
  - flake8
  - black --check .
  - python setup.py check --restructuredtext
  - pytest --cov-report=xml --cov=scvi --internet-tests

after_success:
  - codecov
  - pip list
  - java -jar codacy-coverage-reporter-assembly.jar report -l Python -r coverage.xml

branches:
  only:
  - master
  - dev_v1.0

services:
  - mongodb

before_script:
  - sleep 15  # mongo takes time to start
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
